<script lang="ts" setup>
import CopyIcon from '@/components/CopyIcon.vue'
import { computed, onUnmounted, ref } from 'vue'

interface MetadataEntry {
  key: string
  value: string
}

const imageName = ref('')
const imageUrl = ref('')
const metadataEntries = ref<MetadataEntry[]>([])
const error = ref('')
const isDragging = ref(false)

function formatValue(val: string): string {
  try {
    const parsed = JSON.parse(val)
    return JSON.stringify(parsed, null, 2)
  } catch {
    return val
  }
}

const formattedEntries = computed(() =>
  metadataEntries.value.map((e) => ({
    ...e,
    formatted: formatValue(e.value),
  })),
)

function parsePngChunks(buffer: ArrayBuffer): MetadataEntry[] {
  const bytes = new Uint8Array(buffer)

  // Verify PNG signature
  const signature = [137, 80, 78, 71, 13, 10, 26, 10]
  for (let i = 0; i < 8; i++) {
    if (bytes[i] !== signature[i]) {
      throw new Error('Not a valid PNG file')
    }
  }

  const entries: MetadataEntry[] = []
  let offset = 8

  while (offset < bytes.length) {
    // Read chunk length (4 bytes, big-endian)
    const length =
      (bytes[offset] << 24) |
      (bytes[offset + 1] << 16) |
      (bytes[offset + 2] << 8) |
      bytes[offset + 3]
    offset += 4

    // Read chunk type (4 bytes)
    const type = String.fromCharCode(
      bytes[offset],
      bytes[offset + 1],
      bytes[offset + 2],
      bytes[offset + 3],
    )
    offset += 4

    // Read chunk data
    const data = bytes.slice(offset, offset + length)

    // tEXt chunk: keyword\0text
    if (type === 'tEXt' || type === 'iTXt' || type === 'zTXt') {
      let parsed: { key: string; value: string } | null = null

      if (type === 'tEXt') {
        parsed = parseTextChunk(data)
      } else if (type === 'iTXt') {
        parsed = parseITextChunk(data)
      } else if (type === 'zTXt') {
        parsed = parseZTextChunk(data)
      }

      if (parsed) {
        // ComfyUI stores workflow/prompt metadata
        entries.push(parsed)
      }
    }

    offset += length

    // Skip CRC (4 bytes)
    offset += 4
  }

  return entries
}

function parseTextChunk(data: Uint8Array): { key: string; value: string } | null {
  // tEXt: keyword\0text
  const nullIdx = data.indexOf(0)
  if (nullIdx === -1) return null
  const key = new TextDecoder().decode(data.slice(0, nullIdx))
  const value = new TextDecoder().decode(data.slice(nullIdx + 1))
  return { key, value }
}

function parseITextChunk(data: Uint8Array): { key: string; value: string } | null {
  // iTXt: keyword\0compressionFlag\0compressionMethod\0languageTag\0translatedKeyword\0text
  let pos = 0
  const nulls: number[] = []
  for (let i = 0; i < data.length && nulls.length < 5; i++) {
    if (data[i] === 0) nulls.push(i)
  }
  if (nulls.length < 5) return null

  const key = new TextDecoder().decode(data.slice(0, nulls[0]))
  const text = new TextDecoder().decode(data.slice(nulls[4] + 1))
  return { key, value: text }
}

function parseZTextChunk(data: Uint8Array): { key: string; value: string } | null {
  // zTXt: keyword\0compressionMethod\0compressedText
  // We skip compressed text for simplicity — ComfyUI uses tEXt
  const nullIdx = data.indexOf(0)
  if (nullIdx === -1) return null
  const key = new TextDecoder().decode(data.slice(0, nullIdx))
  // zTXt uses zlib compression; skip unsupported
  return null
}

async function handleFile(file: File) {
  error.value = ''
  metadataEntries.value = []

  // Revoke old URL to avoid memory leaks
  if (imageUrl.value) URL.revokeObjectURL(imageUrl.value)

  imageUrl.value = URL.createObjectURL(file)
  imageName.value = file.name

  try {
    if (!file.type.startsWith('image/')) {
      throw new Error('Please upload an image file')
    }

    const buffer = await file.arrayBuffer()
    const entries = parsePngChunks(buffer)

    if (entries.length === 0) {
      throw new Error(
        'No metadata found in this image. Make sure it was generated by ComfyUI with metadata embedding enabled.',
      )
    }

    metadataEntries.value = entries
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : String(e)
  }
}

function onFileInput(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (file) handleFile(file)
}

function onDragOver(e: DragEvent) {
  e.preventDefault()
  isDragging.value = true
}

function onDragLeave(e: DragEvent) {
  e.preventDefault()
  isDragging.value = false
}

function onDrop(e: DragEvent) {
  e.preventDefault()
  isDragging.value = false
  const file = e.dataTransfer?.files?.[0]
  if (file) handleFile(file)
}
function scrollToKey(key: string) {
  document.getElementById(`key-${key}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })
}

onUnmounted(() => {
  if (imageUrl.value) URL.revokeObjectURL(imageUrl.value)
})


</script>

<template>
  <div class="flex h-full">
    <!-- Left Sidebar -->
    <div class="w-64 border-(0 r solid gray-2) flex flex-col p-4 gap-4 shrink-0 overflow-auto">
      <div class="text-sm text-gray-5">
        <div class="mb-2 font-medium">Upload Image</div>

        <label
          class="flex flex-col items-center justify-center h-32 border-(2 dashed gray-3) rounded-lg cursor-pointer transition-colors hover:border-blue-4"
          :class="{ 'border-blue-5 bg-blue-1': isDragging }"
          @dragover="onDragOver"
          @dragleave="onDragLeave"
          @drop="onDrop"
        >
          <div class="i-carbon:image text-3xl text-gray-4 mb-1" />
          <span class="text-xs text-gray-4">Drop PNG here or click</span>
          <input type="file" accept="image/*" class="hidden" @change="onFileInput" />
        </label>

        <div v-if="imageUrl" class="mt-3">
          <img
            :src="imageUrl"
            :alt="imageName"
            class="w-full rounded border-(1 solid gray-2) object-contain"
          />
        </div>

        <div v-if="imageName" class="mt-2 text-xs text-gray-4 truncate">
          {{ imageName }}
        </div>
      </div>

      <div v-if="metadataEntries.length > 0" class="text-sm text-gray-5">
        <div class="mb-2 font-medium">Keys ({{ metadataEntries.length }})</div>
        <div class="flex flex-col gap-1">
          <button
            v-for="entry in metadataEntries"
            :key="entry.key"
            class="text-xs text-blue-5 hover:underline truncate text-left bg-transparent border-0 cursor-pointer p-0"
            @click="scrollToKey(entry.key)"
          >
            {{ entry.key }}
          </button>
        </div>
      </div>
    </div>

    <!-- Main Content -->
    <div class="flex-1 flex flex-col overflow-hidden">
      <div v-if="error" class="p-4 text-red-5 text-sm bg-red-1 border-(0 b solid red-2)">
        {{ error }}
      </div>

      <div v-if="metadataEntries.length > 0" class="flex-1 overflow-auto p-4">
        <div v-for="entry in formattedEntries" :key="entry.key" :id="`key-${entry.key}`" class="mb-4">
          <div class="flex items-center justify-between mb-1">
            <h3 class="text-sm font-medium text-gray-6">{{ entry.key }}</h3>
            <CopyIcon :text="entry.value" />
          </div>
          <pre class="text-xs font-mono whitespace-pre-wrap break-all bg-gray-1 p-3 rounded border-(1 solid gray-2) overflow-auto">{{ entry.formatted }}</pre>
        </div>
      </div>

      <div
        v-else-if="!error"
        class="flex flex-col items-center justify-center h-full text-gray-4 text-sm gap-2"
      >
        <div class="i-carbon:image text-4xl" />
        <p>Upload a ComfyUI-generated PNG image to extract metadata</p>
      </div>
    </div>
  </div>
</template>

<style lang="less" scoped>
pre {
  &::-webkit-scrollbar {
    width: 6px;
    height: 6px;
  }
  &::-webkit-scrollbar-thumb {
    background: var(--un-colors-gray-3);
    border-radius: 3px;
  }
}
</style>
